#Exercícios Numpy


1 - Importe a biblioteca numpy com o alias "np"

In [2]:
import numpy as np

2 - Crie um array qualquer e informe o tamanho deste vetor em memória.

In [ ]:
np.random.seed(0)
a = np.random.randint(0,10, size=(2,3))
print(f"Tamanho do array em bytes: {a.itemsize * a.size} ")
print(a)
print(a.dtype)

Tamanho do array em bytes: 48 
[[5 0 3]
 [3 7 9]]
int64


3 - Reduza o tamanho do array anterior em memória sem alterar ou excluir nenhum dado e exiba o novo tamanho do array.

In [ ]:
b = a.astype("int8")
print(f"Tamanho do novo array em bytes: {b.itemsize * b.size} ")
print(b)
print(b.dtype)

Tamanho do novo array em bytes: 6 
[[5 0 3]
 [3 7 9]]
int8


4 - Crie um vetor com valores de 10 a 49

In [ ]:
a = np.arange( 10, 50, 1 )
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5 - Inverta o vetor anterior

In [ ]:
a[ : :-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

6- Crie uma matriz 3x3 com valores que variam de 0 a 8

In [ ]:
a = np.random.randint(0,8, size=(3,3))
a

array([[6, 3, 2],
       [7, 4, 2],
       [0, 0, 4]])

7- Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0] (dica: tem função pronta para isso)

In [ ]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)[0]

array([0, 1, 4])

In [ ]:
a = np.array([1,2,0,0,4,0])
b = np.where(a != 0)
b[0]

array([0, 1, 4])

8 - Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo, máximo, média, moda e desvio padrão.

In [ ]:
np.random.seed(1)
a = np.random.randint(50, size=(10,10))
print(a)
print('Mínimo: {}'.format(a.min()))
print('Máximo: {}'.format(a.max()))
print('Média: {}'.format(a.mean()))
print('Moda: {}'.format(np.argmax(np.bincount(a.flatten().astype(int)))))
print('Desvio Padrao: {}'.format(np.std(a)))

[[37 43 12  8  9 11  5 15  0 16]
 [ 1 12  7 45  6 25 20 37 18 20]
 [11 42 28 29 14  4 23 23 41 49]
 [30 32 22 13 41  9  7 22  1  0]
 [17  8 24 13 47 42  8 30  7  3]
 [ 6 21 49  3  4 24 49 43 12 26]
 [16 45 41 18 15  0  4 25 47 34]
 [23  7 26 25 40 22  9  3 39 23]
 [36 27 37 19 38  8 32 34 10 23]
 [15 47 23 25  7 28 10 46 32 24]]
Mínimo: 0
Máximo: 49
Média: 22.07
Moda: 23
Desvio Padrao: 14.179037343910199


9 - Dada uma matriz 1D, multiplique por 10 todos os elementos que estão entre 3 e 8.

In [ ]:
a = np.arange(10)
a[(a >= 3) & (a <= 8)]*10

array([30, 40, 50, 60, 70, 80])

In [ ]:
a = np.arange(10)

# Encontre os índices dos elementos que estão entre 3 e 8
indices = np.where((a >= 3) & (a <= 8))

# Multiplique os elementos nessas posições por 10
a[indices] *= 10

# Imprima a matriz resultante
a

array([ 0,  1,  2, 30, 40, 50, 60, 70, 80,  9])

10 - Crie uma matriz 5x5 com valores de linha variando de 0 a 4

In [ ]:
np.random.seed(0)
a = np.random.randint(0,5, size=(5,5))
a

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4],
       [3, 0, 3, 0, 2]])

11 - Crie um vetor de inteiros aleatório de tamanho 10 e ordene-o

In [ ]:
np.random.seed(1)
a = np.random.randint(99, size=(10))
np.sort(a)

array([ 1,  5,  9, 12, 16, 37, 64, 72, 75, 79])

12 - Crie o mesmo vetor da questão anterior (com o mesmo seed) e exiba a ordem de seus índices (função argsort)

In [ ]:
np.random.seed(1)
a = np.random.randint(99, size=(10))
print(f"array: {a}\nordem indices: {np.argsort(a)}")
a[np.argsort(a)] #ordenando

array: [37 12 72  9 75  5 79 64 16  1]
ordem indices: [9 5 3 1 8 0 7 2 4 6]


array([ 1,  5,  9, 12, 16, 37, 64, 72, 75, 79])

13 - Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0

In [ ]:
a = np.random.randint(99, size=(10))
print(f"Vetor: {a}\nIndice valor maximo: {np.argmax(a)}")
a[np.argmax(a)] = 0
print(f"Vetor valor max subst 0: {a}")

Vetor: [ 8 88 13 47 72 30 71  3 70 21]
Indice valor maximo: 1
Vetor valor max subst 0: [ 8  0 13 47 72 30 71  3 70 21]


14 - Crie uma matriz 3x3 e exiba o índice e o valor de cada posição. (dica: consulte as funções np.ndenumerate e np.ndindex)

In [ ]:
np.random.seed(1)
a = np.random.randint(99, size=(3,3))
print(a)
for indice, valor in np.ndenumerate(a):
    print(f"Posição {indice}: {valor}")

[[37 12 72]
 [ 9 75  5]
 [79 64 16]]
Posição (0, 0): 37
Posição (0, 1): 12
Posição (0, 2): 72
Posição (1, 0): 9
Posição (1, 1): 75
Posição (1, 2): 5
Posição (2, 0): 79
Posição (2, 1): 64
Posição (2, 2): 16


15- Como ordenar uma matriz pela enésima coluna?

In [4]:
# Opcao 1 - Extraindo e ordenando coluna
np.random.seed(1)
a = np.random.randint(99, size=(3,3))
print(f"Matriz:\n{a}")

coluna_ordenar = 1
vetor_ordenado_enesima_coluna = np.sort(a[:, coluna_ordenar])
a[:, coluna_ordenar] = vetor_ordenado_enesima_coluna

print(f"\nMatriz Ordenada pela coluna {coluna_ordenar}:\n{a}")

Matriz:
[[37 12 72]
 [ 9 75  5]
 [79 64 16]]

Matriz Ordenada pela coluna 1:
[[37 12 72]
 [ 9 64  5]
 [79 75 16]]


In [6]:
# Opcao 2 - Ordenando nova matriz inteira
np.random.seed(1)
a = np.random.randint(99, size=(3,3))
print(f"Matriz:\n{a}")

a_ordenada_todas_colunas = np.sort(a, axis= 0)
enesima_coluna = 1
a[:, enesima_coluna] = a_ordenada_todas_colunas[:, enesima_coluna]

print(f"\nMatriz Ordenada pela coluna {enesima_coluna}:\n{a}")

Matriz:
[[37 12 72]
 [ 9 75  5]
 [79 64 16]]

Matriz Ordenada pela coluna 1:
[[37 12 72]
 [ 9 64  5]
 [79 75 16]]
